// www/src/app/log/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {TitleService} from "../../Services/title.service";
import {HttpService} from "../../Services/http.service";
import {Router} from "@angular/router";
import {TokenService} from "../../Services/token.service";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username: string = '';
  password: string = '';

  constructor(
    private titleSrv: TitleService,
    private httpSrv: HttpService,
    private router: Router,
    private token: TokenService
  ) { }

  ngOnInit() {
    if(this.token.logged()) {
      this.router.navigate(['']);
    }
    this.titleSrv.setTitle('Login');
  }

  submit() {
    this.httpSrv.post('/login',
      {
        username : this.username,
        password : this.password
      }
    ).then(result => {
      // TODO reload page
      this.router.navigate(['']);
    }).catch(error => console.error(error));
  }

}

<div class="container">
  <div class="login-container">
    <div id="output"></div>
    <div class="avatar"></div>
    <div class="form-box">
      <form action="" (ngSubmit)="submit()">
        <input type="text"     name="user"     placeholder="username" [(ngModel)]="username" required />
        <input type="password" name="password" placeholder="password" [(ngModel)]="password" required />
        <button class="btn btn-info btn-block login" type="submit">Login</button>
      </form>
    </div>
  </div>
</div>

// www-vue/nuxt/components/Login.vue
<template>
  <div class="container">
    <div class="login-container">
      <div id="output"></div>
      <div class="avatar"></div>
      <div class="form-box">
        <form >
          <input
            type="text"
            name="user"
            placeholder="Username"
            v-model="username"
            required
          />
          <input
            type="password"
            name="password"
            placeholder="Password"
            v-model="password"
            required
          />
          <button
            class="btn btn-info btn-block login"
            type="button"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  </div>
</template>
<script>
  import Http from '../plugins/Http'

  export default {
    name : 'login',
    data() {
      return {
        username : '',
        password : ''
      }
    },
    created() {
      Http.get();
    },
    methods: {

    }
  }
</script>
