// www-vue/nuxt/components/Login.vue
<template>
  <div class="container">
    <div class="login-container">
      <div id="output"></div>
      <div class="avatar"></div>
      <div class="form-box">
        <form >
          <input
            type="text"
            name="user"
            placeholder="Username"
            v-model="username"
            required
          />
          <input
            type="password"
            name="password"
            placeholder="Password"
            v-model="password"
            required
          />
          <button
            class="btn btn-info btn-block login"
            type="button"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  </div>
</template>
<script>
  import Http from '../plugins/Http'

  export default {
    name : 'login',
    data() {
      return {
        username : '',
        password : ''
      }
    },
    created() {
      Http.get();
    },
    methods: {

    }
  }
</script>

// www/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {TitleService} from "../Services/title.service";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(
    private titleSrv: TitleService
  ) { }

  ngOnInit() {
    this.titleSrv.setTitle('Login');

  }

}

<div class="container">
  <div class="login-container">
    <div id="output"></div>
    <div class="avatar"></div>
    <div class="form-box">
      <form action="" method="">
        <input name="user" type="text" placeholder="username">
        <input type="password" placeholder="password">
        <button class="btn btn-info btn-block login" type="submit">Login</button>
      </form>
    </div>
  </div>
</div>
